# Generated by Django 3.1.7 on 2021-03-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210310_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
