# Generated by Django 3.1.7 on 2021-03-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210311_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='times_taken',
        ),
    ]
