# Generated by Django 3.1.7 on 2021-03-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quiz_times_taken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='points',
            new_name='point',
        ),
        migrations.AlterField(
            model_name='option',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='quiz.quiz'),
        ),
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quiz', to='quiz.quiz')),
            ],
        ),
    ]
