# Generated by Django 3.1.7 on 2021-03-11 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0006_auto_20210311_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scoreboard', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='quiz.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scoreboard', to='quiz.quiz'),
        ),
    ]
