# Generated by Django 3.1.7 on 2021-03-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210311_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Quizzes'},
        ),
    ]
