# Generated by Django 3.1.7 on 2021-03-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210311_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreboard',
            options={'verbose_name_plural': 'Score Board'},
        ),
    ]
