# Generated by Django 3.1.7 on 2021-03-11 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20210311_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='schedule_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 11, 58, 1, 338738)),
        ),
    ]
