# Generated by Django 3.1.7 on 2021-03-11 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_quiz_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='schedule_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 11, 58, 53, 465624, tzinfo=utc)),
        ),
    ]
