# Generated by Django 3.1.7 on 2021-03-11 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20210311_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='schedule_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
