# Generated by Django 3.1.7 on 2021-03-11 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20210311_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='timelimit',
            field=models.DurationField(default=datetime.timedelta(seconds=1200)),
        ),
    ]
