# Generated by Django 3.1.7 on 2021-03-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_quiz_timelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='available_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_questions_num',
            field=models.IntegerField(default=10),
        ),
    ]
