# Generated by Django 3.1.7 on 2021-04-06 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0016_auto_20210311_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='scores',
            field=models.ManyToManyField(related_name='quizzes', through='quiz.ScoreBoard', to=settings.AUTH_USER_MODEL),
        ),
    ]
